### ISSUE TITLE
textField不走代理

### ISSUE THREAD

**Issue by Gerhard94** [parkingwang/vehicle-keyboard-ios#10]
textfield放在uitableViewCell上面 不用这个键盘的话会走textField的代理方法，如果用了就不走了

**Comment by yzhtracy** [comment]
如果是使用的UItextField,因为用的非系统键盘 ，所以不会走UItextfield的代理。可以通过kvo来监听它的text值。

**Comment by Gerhard94** [comment]
> 如果是使用的UItextField,因为用的非系统键盘 ，所以不会走UItextfield的代理。可以通过kvo来监听它的text值。

尝试过 没有调起kvo的方法

**Comment by noveleven** [comment]
@yzhtracy text可以kvo，但是 `textFieldShouldReturn:` 也没见调用啊

**Comment by noveleven** [comment]
文档不是说直接当直接当做系统UItextfield使用即可么？！

**Comment by Tian-WJ** [comment]
同问：textfield放在UICollectionViewCell上面,不用这个键盘的话会走textField的代理方法，如果用了就不走了，textFieldShouldReturn也不见调起

**Comment by RenChuanChuan** [comment]
确实，有什么解决办法吗

**Comment by RenChuanChuan** [comment]
> 虽然我在使用时解决了这个问题，但还是希望作者维护的时候能把这个功能完善下。支持开源！加油

在UITableViewCell或者UICollectionViewCell里面，添加系统键盘弹出/收起观察者：

    [[NSNotificationCenter defaultCenter] addObserver:self
                                       selector:@selector(keyboardDidShow:)
                                          name: UIKeyboardDidShowNotification
                                         object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                       selector:@selector(keyboardDidHide:)
                                          name: UIKeyboardDidHideNotification
                                         object:nil];

///实现观察方法
- (void)keyboardDidShow:(NSNotification *)notif {
    NSLog(@"键盘打开");
}

- (void)keyboardDidHide:(NSNotification *)notif {
    NSLog(@"键盘关闭");
    ///在这里拿到textField的值进行显示或回传Controller，因为键盘收起其实就是确定和完成都包含的动作，取值时机相同。
}

**Comment by yzhtracy** [comment]
在1.0.7版本，已解决。新增系统输入框车牌键盘的一些事件监听。
